# Generated by Django 2.0.4 on 2018-04-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uid',
            field=models.CharField(default='39bc59ea', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
